apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: unalmeet.page
    http:
      paths: 
      - backend:
          serviceName: unalmeet-wa-service
          servicePort: 80
