apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: http://35.238.39.80/
    http:
      paths: 
      - backend:
          serviceName: hello-v1
          servicePort: 80
