apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
spec:
    tls:
    - hosts:
      - unalmeet.page
      secretName: unal-tls
    rules:
      - host: unalmeet.page
        http: 
          paths: 
          - path: /
            backend:
              serviceName: unalmeet-wa-service
              servicePort: 80