apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
spec:
    tls:
    - hosts:
      - unalmeet.edu.com
      secretName: unal-tls
    rules:
      - host: unalmeet.edu.com 
        http: 
          paths: 
          - path: /
            backend:
              serviceName: hello-v1
              serviceNPort: 80