apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
spec:
    tls:
    - hosts:
      - http://35.238.39.80/
      secretName: unal3-tls
    rules:
      - host: http://35.238.39.80/
        http: 
          paths: 
          - path: /
            backend:
              serviceName: hello-v1
              servicePort: 80