apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production
  namespace: default
spec:
  dnsNames:
    - unalmeet.com
  secretName: unal5-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer