apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-v1
  namespace: default
spec:
  dnsNames:
    - unalmeet.com
  secretName: unal3-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer