apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - unalmeet.page
    secretName: unal1-tls
  rules:
  - host: unalmeet.page
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          serviceName: hello-v1 #unalmeet-wa-service
          servicePort: 80
