apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
spec:
    tls:
    - hosts:
        -  unalmeet.edu.com # Nuestro nombre de dominio configurado en el DNS
        secretName: unal-tls # (debe ser lower case) este nombre lo tomara automáticamente nuestro Issuer (Emisor) para generar el SECRET.
    rules:
    - host: unalmeet.edu.com #Nuestro nombre de dominio configurado en el DNS
        http: &http_rules
        paths:
        - path: 
            backend:
            serviceHost: http://localhost/CC/
            serviceName: #Poner el nombre del servicio